### ISSUE TITLE
It opens but once it starts it closes

### ISSUE THREAD

**Issue by VenomRAT35** [stepacool/Eye-Tracker#5]
Traceback (most recent call last):
  File "main.py", line 45, in update_frame
    self.display_image(base_image)
  File "main.py", line 100, in display_image
    if len(img.shape) == 3:
AttributeError: 'NoneType' object has no attribute 'shape'
Abort trap: 6

**Comment by Oysiyl** [comment]
Change `self.capture = cv2.VideoCapture(cv2.CAP_DSHOW)` **at line 28** in **main.py** to `self.capture = cv2.VideoCapture(0)` helps me. It's look like cv2.CAP_DSHOW is work for only one frame or something and immediately closed after that.
