### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by bessalahAmar** [stepacool/Eye-Tracker#9]
Exception after clicking the start button : 

Traceback (most recent call last):
  File "main.py", line 45, in update_frame
    self.display_image(base_image)
  File "main.py", line 100, in display_image
    if len(img.shape) == 3:
AttributeError: 'NoneType' object has no attribute 'shape'
Abandon (core dumped)

**Comment by stepacool** [comment]
Hello, the exception occurred because there's no image in your program - meaning no camera, or your camera is under a different ID on your PC. Try changing lines 28-30 in the main.py file.
